swagger: '2.0'

info:
  version: "1.0.0"
  title: SistemaProcessual
  description: Micro-serviço para obter dados em sistemas processuais

basePath: /sisproc/api/v1
schemes: [http,https]
consumes: [application/json]
produces: [application/json]

tags:
  - name: proc
    description: Dados de processos
  - name: utils
    description: Utilitários

paths:
  /autenticar:
    post:
      description: Autenticar usuário
      tags: [utils]
      parameters:
        - $ref: "#/parameters/login"
        - $ref: "#/parameters/senha"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              nome:
                $ref: "#/definitions/Nome"
              cpf:
                $ref: "#/definitions/CPF"
              email:
                $ref: "#/definitions/Email"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
  /peticao/intercorrente/tipos:
    get:
      description: Tipos de petição intercorrente
      tags: [utils]
      parameters: []
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/TipoPeticaoIntercorrente"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /processo/validar/{numero}:
    get:
      description: Validar o número do processo
      tags: [utils]
      parameters:
        - $ref: "#/parameters/numero"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              numero:
                $ref: "#/definitions/Numero"
              orgao:
                $ref: "#/definitions/Orgao"
              unidade:
                $ref: "#/definitions/Unidade"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /processo/{numero}/pdf:
    get:
      description: Obter o PDF completo pelo número do processo 
      tags: [utils]
      produces: [application/pdf]
      parameters:
        - $ref: "#/parameters/numero"
      responses:
        200:
          description: Successful response
          schema:
            type: file
          headers:
            Content-Type:
              type: string
              description: application/pdf
            Content-Disposition:
              type: string
              description: attachment; filename=processo.pdf
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /usuario-web/{username}:
    get:
      description: Obter dados de um usuário web, ou autenticar usando Basic Authentication
      tags: [utils]
      parameters:
        - $ref: "#/parameters/username"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              nome:
                $ref: "#/definitions/Nome"
              cpf:
                $ref: "#/definitions/CPF"
              email:
                $ref: "#/definitions/Email"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /usuario-web/{username}/peticao-intercorrente/contar:
    get:
      description: Validar o número do processo
      tags: [utils]
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/dias"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/Contagem"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /usuario-web/{username}/peticao-intercorrente/listar:
    get:
      description: Validar o número do processo
      tags: [utils]
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/data"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/PeticaoIntercorrente"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /classe-cnj/{id}:
    get:
      description: Obter dados de uma classe pela id
      tags: [utils]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/orgaoquery"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              codigo:
                $ref: "#/definitions/Codigo"
              descricao:
                $ref: "#/definitions/Descricao"
              ativo:
                $ref: "#/definitions/Ativo"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /assunto-cnj/{id}:
    get:
      description: Obter dados de um assunto pela id
      tags: [utils]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/orgaoquery"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              codigo:
                $ref: "#/definitions/Codigo"
              descricao:
                $ref: "#/definitions/Descricao"
              ativo:
                $ref: "#/definitions/Ativo"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

parameters:
  numero:
    name: numero
    in: path
    description: Número do processo só algarismos
    required: true
    type: string
  login:
    name: login
    in: formData
    description: Login do usuário
    required: true
    type: string
  senha:
    name: senha
    in: formData
    description: Senha do usuário
    required: true
    type: string
  username:
    name: username
    in: path
    description: Login do usuário
    required: true
    type: string
  dias:
    name: dias
    in: query
    description: Quantidade de dias a serem consultados
    required: true
    type: string
  data:
    name: data
    in: query
    description: Data a ser consultada
    required: true
    type: string
  id:
    name: id
    in: path
    description: Número da id só algarismos
    required: true
    type: string
  orgaoquery:
    name: orgao
    in: query
    description: Órgao
    required: true
    type: string
            
definitions:
  Nome:
    type: string
    description: Nome do usuário
    example: Renato Crivano
    
  CPF:
    description: CPF do usuário
    type: string      
    example: 11122233344
    
  Email:
    description: Email do usuário
    type: string
    example: rcrivano@teste.com

  TipoPeticaoIntercorrente:
    description: Tipo de petição intercorrente
    type: object
    properties:
      id:
        type: string
      descricao:
        type: string
      orgao:
        type: string

  Contagem:
    description: Data e quantidade de itens
    type: object
    properties:
      data:
        type: string
      quantidade:
        type: string

  PeticaoIntercorrente:
    description: Petição intercorrente
    type: object
    properties:
      processo:
        type: string
      protocolo:
        type: string
      dataprotocolo:
        type: string
      classe:
        type: string
      unidade:
        type: string
      orgao:
        type: string

  Numero:
    description: Número do processo
    type: string
    example: 00002294020154020000

  Orgao:
    description: Órgão do processo
    type: string
    example: JFRJ

  Unidade:
    description: Unidade do processo
    type: string
    example: 01JEF

  Codigo:
    type: string
    description: Código
    
  Descricao:
    type: string
    description: Descrição
    
  Ativo:
    type: boolean
    description: Ativo true ou false
    
  Error:
    type: object
    properties:
      error:
        type: string
    example:
      error: Não foi possível realizar a operação