swagger: '2.0'

info:
  version: "1.0.0"
  title: Balcao Virtual
  description: Micro-serviço para obter indicadores de gestão

# host: assijus.jfrj.jus.br
basePath: /balcaovirtual/api/v1
schemes: [http,https]
consumes: [application/json]
produces: [application/json]

tags:
  - name: stats
    description: Obter estatísticas


################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  nome:
    name: nome
    in: formData
    description: Nome do usuário
    type: string
    required: false
  email:
    name: email
    in: formData
    description: Email do usuário
    type: string
    required: false
  mensagem:
    name: mensagem
    in: formData
    description: Sugestão
    type: string
    required: true
  username:
    name: username
    in: formData
    description: Identificador do usuário
    type: string
    required: true
  password:
    name: password
    in: formData
    description: Senha do usuário
    type: string
    required: true
  orgao:
    name: orgao
    in: formData
    description: Órgão do processo
    required: true
    type: string
  numero:
    name: numero
    in: path
    description: Número do processo só algarismos
    required: true
    type: string
  tipopeticao:
    name: tipopeticao
    in: formData
    description: Código do tipo da petição
    type: string
    required: true
  nivelsigilo:
    name: nivelsigilo
    in: formData
    description: Código do nivel de sigilo
    type: string
    required: true
  pdfs:
    name: pdfs
    in: formData
    description: Referência para os PDFs que foram enviados previamente para o servidor, separadas por vírgula
    type: string
    required: true
  pdf:
    name: pdf
    in: path
    description: Referência para o PDF que foi enviado previamente para o servidor
    type: string
    required: true
  data:
    name: data
    in: query
    description: Data a ser consultada
    required: true
    type: string
  id:
    name: id
    in: path
    description: Número da id só algarismos
    required: true
    type: string
  jwt:
    name: jwt
    in: path
    description: JWT que referencia um artefato a ser baixado
    required: true
    type: string
  orgaoquery:
    name: orgao
    in: query
    description: Órgao
    required: true
    type: string

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /sugestao:
    post:
      parameters:
        - $ref: "#/parameters/nome"
        - $ref: "#/parameters/email"
        - $ref: "#/parameters/mensagem"
      description: Enviar sugestões
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              status:
                type: string
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
  /sessions/create:
    post:
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/password"
      description: Autenticar usuário
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              id_token:
                type: string
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
  /config/peticao/intercorrente/tipos:
    get:
      description: Tipos de petição intercorrente
      tags: [utils]
      parameters: []
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/ConfigTipoPeticaoIntercorrente"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
  /processo/{numero}/validar:
    get:
      description: Validar o número do processo
      tags: [utils]
      parameters:
        - $ref: "#/parameters/numero"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              orgao:
                $ref: "#/definitions/Orgao"
              unidade:
                $ref: "#/definitions/Unidade"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
  /processo/{numero}/peticionar:
    post:
      description: Enviar petições para um processo
      tags: [utils]
      parameters:
        - $ref: "#/parameters/numero"
        - $ref: "#/parameters/orgao"
        - $ref: "#/parameters/tipopeticao"
        - $ref: "#/parameters/nivelsigilo"
        - $ref: "#/parameters/pdfs"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              status:
                type: string
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
  /processo/{numero}/consultar:
    get:
      description: Enviar petições para um processo
      tags: [utils]
      parameters:
        - $ref: "#/parameters/numero"
        - $ref: "#/parameters/orgaoquery"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              payload:
                type: string
                format: byte
                description: PDF codificado em base64
              contenttype:
                type: string
                description: Constante em application/pdf
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /processo/{numero}/peca/{id}/pdf:
    get:
      description: Obter o PDF de uma peça processual para visualização
      tags: [view]
      parameters:
        - $ref: "#/parameters/numero"
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/orgaoquery"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              jwt:
                type: string
                description: JWT com as informações para download do PDF
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /download/{jwt}:
    get:
      description: Faz o download de um artefato qualquer
      tags: [view]
      parameters:
        - $ref: "#/parameters/jwt"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              payload:
                type: string
                format: byte
                description: PDF codificado em base64
              contenttype:
                type: string
                description: Constante em application/pdf
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
            
  /arquivo-temporario/{pdf}:
    get:
      description: Obter o PDF de um documento para visualização
      tags: [view]
      parameters:
        - $ref: "#/parameters/pdf"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              payload:
                type: string
                format: byte
                description: PDF codificado em base64
              contenttype:
                type: string
                description: Constante em application/pdf
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /peticao-intercorrente/contar:
    get:
      description: Validar o número do processo
      tags: [utils]
      parameters: []
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/QuantidadePorData"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /peticao-intercorrente/listar:
    get:
      description: Validar o número do processo
      tags: [utils]
      parameters: 
        - $ref: "#/parameters/data"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/PeticaoIntercorrenteResumo"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /aviso/listar:
    get:
      description: Listar as intimações para o usuário logado
      tags: [utils]
      parameters: []
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/Aviso"
              status:
                type: array
                items:
                  $ref: "#/definitions/ListStatus"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /classe/{id}:
    get:
      description: Obter dados de uma classe pela id
      tags: [utils]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/orgaoquery"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              codigo:
                $ref: "#/definitions/Codigo"
              descricao:
                $ref: "#/definitions/Descricao"
              descricaocompleta:
                $ref: "#/definitions/DescricaoCompleta"
              ativo:
                $ref: "#/definitions/Ativo"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"

  /assunto/{id}:
    get:
      description: Obter dados de um assunto pela id
      tags: [utils]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/orgaoquery"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              codigo:
                $ref: "#/definitions/Codigo"
              descricao:
                $ref: "#/definitions/Descricao"
              descricaocompleta:
                $ref: "#/definitions/DescricaoCompleta"
              ativo:
                $ref: "#/definitions/Ativo"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"


################################################################################
#                                     Definitions                              #
################################################################################
definitions:
  ConfigTipoPeticaoIntercorrente:
    description: Tipo de petição intercorrente
    type: object
    properties:
      id:
        type: string
      descricao:
        type: string
      orgao:
        type: string

  Orgao:
    description: Órgão do processo
    type: string
    example: JFRJ

  Unidade:
    description: Unidade do processo
    type: string
    example: 01JEF

  QuantidadePorData:
    description: Data e quantidade de itens
    type: object
    properties:
      data:
        type: string
      quantidade:
        type: string

  PeticaoIntercorrenteResumo:
    description: Petição intercorrente
    type: object
    properties:
      processo:
        type: string
      protocolo:
        type: string
      dataprotocolo:
        type: string
      classe:
        type: string
      unidade:
        type: string
      orgao:
        type: string

  Aviso:
    description: Aviso
    type: object
    properties:
      idaviso:
        type: string
      dataaviso:
        type: string
      processo:
        type: string
      unidade:
        type: string
      unidadenome:
        type: string
      unidadetipo:
        type: string
      orgao:
        type: string
      localidade:
        type: string

  ListStatus:
    type: object
    properties:
      system:
        type: string
        description: Identificador do sistema integrado
      errormsg:
        type: string
        description: Mensagem de erro se houver
      stacktrace:
        type: string
        description: Detalhamento do erro

  Codigo:
    type: string
    description: Código
    
  Descricao:
    type: string
    description: Apenas o nível mais específico da descrição
    
  DescricaoCompleta:
    type: string
    description: Descrição incluindo todos os níveis superiores
    
  Ativo:
    type: boolean
    description: Ativo true ou false
    
  Error:
    type: object
    properties:
      error:
        type: string